version: "3.2"

services:
  dev:
    container_name: genesis-dao
    image: paritytech/ci-linux:production
    working_dir: /var/www/genesis-dao
    ports:
      - "0.0.0.0:9944:9944"
    environment:
      - CARGO_HOME=/var/www/genesis-dao/.cargo
    volumes:
      - .:/var/www/genesis-dao
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release --features local-node && ./target/release/genesis-dao --dev --ws-external"
