[package]
name = "integration_wrapper"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
parity-scale-codec = "3.3.0"
sp-keyring = "12.0.0" # needs to match the version used in subxt!
subxt = "0.26.0"
tokio = "1.25.0"

